import type { PricingPlan } from '@/types'

export const pricingPlans: PricingPlan[] = [
  {
    id: 'starter',
    name: 'Starter',
    price: 1499,
    currency: 'USD',
    period: 'one-time',
    description: 'Perfect for small businesses and startups getting online for the first time.',
    cta: 'Get Started',
    features: [
      'Up to 5 pages',
      'Mobile responsive design',
      'Contact form integration',
      'Basic SEO setup',
      'Google Analytics setup',
      'Social media links',
      '2 rounds of revisions',
      '30-day post-launch support',
    ],
    notIncluded: [
      'CMS Integration',
      'E-commerce functionality',
      'Custom animations',
      'Priority support',
    ],
  },
  {
    id: 'professional',
    name: 'Professional',
    price: 3499,
    currency: 'USD',
    period: 'one-time',
    description: 'Ideal for growing businesses that need a powerful, feature-rich website.',
    cta: 'Get Started',
    highlighted: true,
    badge: 'Most Popular',
    features: [
      'Up to 15 pages',
      'Premium custom design',
      'CMS integration (Blog / News)',
      'Advanced SEO optimization',
      'Framer Motion animations',
      'Google Analytics + Search Console',
      'Speed optimization',
      'Unlimited revisions',
      '90-day post-launch support',
      'Performance report',
    ],
    notIncluded: [
      'E-commerce functionality',
      'Custom integrations',
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 0,
    currency: 'USD',
    period: 'custom',
    description: 'Full-scale solutions for established companies with complex requirements.',
    cta: 'Request Quote',
    features: [
      'Unlimited pages',
      'Bespoke UI/UX design',
      'E-commerce functionality',
      'Custom third-party integrations',
      'Advanced animations',
      'Multi-language support',
      'Dedicated project manager',
      'Priority development queue',
      '12-month support & maintenance',
      'Monthly performance reports',
      'SLA guarantee',
    ],
  },
]
